# Generated by Django 2.2.6 on 2021-05-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210518_0007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostForm',
            new_name='NewPost',
        ),
    ]
