# Generated by Django 2.2.6 on 2021-05-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210519_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
